require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - "bin/**/*"
    - "db/migrate/*.rb"
    - "lib/tasks/auto_annotate_models.rake"
    - "db/schema.rb"
    - "node_modules/**/*"
    - "vendor/**/*"

Layout/LineLength:
  Max: 90
  AllowedPatterns: ["^ *# "]

Metrics/BlockLength:
  AllowedMethods:
    - "configure"
    - "context"
    - "describe"
    - "factory"
    - "ActiveRecord::Schema.define"
    - "FactoryBot.define"
    - "RSpec.shared_examples"

RSpec/ExampleLength:
  Max: 12
